api_platform:
  # The title of the API.
  title: 'Edu API'

  # The description of the API.
  description: 'Edu API description'

  # The version of the API.
  version: '0.0.1'

  show_webby: false

  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    xml: [ 'application/xml', 'text/xml' ]
    csv: [ 'text/csv' ]
    html: [ 'text/html' ]

  swagger:
    versions: [3]

  eager_loading:
      fetch_partial: true

  enable_swagger: true
  enable_swagger_ui: true
  enable_profiler: true

  use_symfony_listeners: true
