monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:

            redis:
                host: 127.0.0.1
                port: 6379
                path: "%kernel.logs_dir%/%kernel.environment%_redis.log"
                type: stream
                channels: [cache]

            error_log:
                level: error
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%_error.log"


            debug_info:
                level: debug
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
                channels: [  "!deprecations", '!cache' ]

            info:
                level: info
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%_info.log"
                channels: [  "!deprecations", '!cache' ]


#            main:
#                type: stream
#                path: "%kernel.logs_dir%/%kernel.environment%_app.log"
#                level: debug
#                channels: [  ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ console  ]
                path: "%kernel.logs_dir%/%kernel.environment%_console.log"

            security:
                # log all messages (since debug is the lowest level)
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%_security.log'
                channels: [ security ]

            doctrine:
                # log all messages (since debug is the lowest level)
                level: critical
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%_critical_doctrine.log'
                channels: [ doctrine ]

            doctrine_debug:
                # log all messages (since debug is the lowest level)
                level: debug
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%_info_doctrine.log'
                channels: [ doctrine ]

            request:
                # log all messages (since debug is the lowest level)
                level: warning
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%_request.log'
                channels: [ request ]

            deprecation:
                type: stream
                channels: [ deprecation ]
                path: '%kernel.logs_dir%/%kernel.environment%_deprecation.log'

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
