nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    expose_headers: [ 'Link' ]
    forced_allow_origin_value: ~
    skip_same_as_origin: true
    max_age: 3600
  paths:
    '^/':
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_headers: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      forced_allow_origin_value: ~
      max_age: 3600