version: "3.8"

services:
  symfony-fakestore-php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: docker
      dockerfile: ./php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/
      -  ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony-fakestore
    links:
      - symfony-fakestore-redis

  symfony-fakestore-nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:rw
      - ./docker/php-fpm/php.ini:/etc/php/8.1/cli/php.ini
    depends_on:
      - symfony-fakestore-php-fpm
    networks:
      - symfony-fakestore

  symfony-fakestore-database:
    image: 'postgres:alpine'
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    volumes:
     - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_BASE}
    ports:
        - "5432:5432"
    networks:
        - symfony-fakestore


  symfony-fakestore_mailer:
    image: sj26/mailcatcher:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailer
    restart: always
    expose:
      - '1025'
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - symfony-fakestore
#  mailer:
#    image: maildev/maildev
#    container_name: ${COMPOSE_PROJECT_NAME}_mailer
#    ports:
#      - "1025"
#      - "1080"
#    networks:
#      - symfony-fakestore

  symfony-fakestore-redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - symfony-fakestore

  symfony-fakestore-rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}_rabbit
    image: rabbitmq:3-management
    restart: always
    command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      timeout: 5s
      retries: 1
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./docker/rabbitmq/:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - symfony-fakestore

networks:
  symfony-fakestore:
    driver: bridge

volumes:
  symfony-fakestore-database: